### ISSUE TITLE
Cymon API

### ISSUE THREAD

**Issue by CyberTaoFlow** [eSentire/django-cymon-firewall#1]
Greetings!

I am interested in cymon as a threat intelligence source however I could not find anything about gaining API access or acceptable use of cymon.io.   I could scrape the page for intel but would rather not piss anyone off or cause issues etc.  Is cymon.io simply a brand new offering by esentire that has not had the supporting material developed yet?

**Comment by r0yfire** [comment]
Cymon is still an experimental system. We are working on documentation and other supporting materials for it, as you guessed. It is a free service, which may offer premium features in the future.
We have a preliminary API that you can use, but keep in mind that it may change. You can access it using the following URL:
http://cymon.io/api/public/nexus?ip=58.218.211.29

The API should not be used in commercial applications until we publish an official Terms of Use.
Don't forget to share your results/comments with us.

**Comment by CyberTaoFlow** [comment]
cool thanks! Ill stick to doing manual queries using for loops or something.
